// This file is generated by the build_runner package.
// Do not edit this file by hand.

import 'package:flutter/services.dart';
import 'package:mockito/annotations.dart';
import 'package:shared_preferences/shared_preferences.dart';

export 'mocks.mocks.dart';

@GenerateMocks([SharedPreferences, MethodChannel])
void main() {}
