// Mocks generated by Mockito 5.4.5 from annotations
// in pokeapi/test/features/pokemon_list/domain/repositories/pokemon_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pokeapi/features/pokemon_list/data/adapters/poke_api_adapter.dart'
    as _i4;
import 'package:pokeapi/features/pokemon_list/data/models/pokemon_model.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePokemonModel_1 extends _i1.SmartFake implements _i3.PokemonModel {
  _FakePokemonModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PokeApiAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokeApiAdapter extends _i1.Mock implements _i4.PokeApiAdapter {
  MockPokeApiAdapter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i5.Future<List<_i3.PokemonModel>> getPokemons({
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPokemons, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i5.Future<List<_i3.PokemonModel>>.value(
              <_i3.PokemonModel>[],
            ),
          )
          as _i5.Future<List<_i3.PokemonModel>>);

  @override
  _i5.Future<_i3.PokemonModel> getPokemonById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPokemonById, [id]),
            returnValue: _i5.Future<_i3.PokemonModel>.value(
              _FakePokemonModel_1(
                this,
                Invocation.method(#getPokemonById, [id]),
              ),
            ),
          )
          as _i5.Future<_i3.PokemonModel>);

  @override
  _i5.Future<List<_i3.PokemonModel>> searchPokemons(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchPokemons, [query]),
            returnValue: _i5.Future<List<_i3.PokemonModel>>.value(
              <_i3.PokemonModel>[],
            ),
          )
          as _i5.Future<List<_i3.PokemonModel>>);
}
